# Generated by Django 4.1.2 on 2022-10-09 16:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.CharField(max_length=60)),
                ('api_key', models.CharField(max_length=60)),
                ('bot_hdlr_cmd', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_text', models.TextField()),
                ('is_reply', models.BooleanField(default=False)),
                ('send_date', models.DateTimeField(default=datetime.datetime(2022, 10, 9, 18, 2, 15, 128198))),
                ('delivery_date', models.DateTimeField()),
                ('read_date', models.DateTimeField()),
                ('recipient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msgapp.recipient')),
                ('telegram_bot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msgapp.telegrambot')),
            ],
        ),
    ]
