# Generated by Django 4.1.2 on 2022-10-09 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='telegram_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='telegrambot',
            name='api_key',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='telegrambot',
            name='bot_name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='telegrammsg',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 9, 20, 44, 2, 912040)),
        ),
    ]
