# Generated by Django 4.1.2 on 2022-10-11 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgapp', '0003_remove_telegrammsg_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammsg',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 15, 7, 18, 682528)),
        ),
    ]
