# Generated by Django 4.1.2 on 2022-10-11 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgapp', '0004_alter_telegrammsg_send_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammsg',
            name='message_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='telegrammsg',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 11, 15, 8, 43, 195803)),
        ),
    ]
