# Generated by Django 4.1.2 on 2022-10-12 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('msgapp', '0005_telegrammsg_message_id_alter_telegrammsg_send_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='sent_via_bot',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='telegrammsg',
            name='message_id',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='telegrammsg',
            name='send_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
