# Generated by Django 4.1.2 on 2022-10-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgapp', '0006_telegrambot_sent_via_bot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammsg',
            name='is_reply',
            field=models.BooleanField(default=True),
        ),
    ]
